config/routes.rb
Rails.application.routes.draw do

  get 'reviews/new'

  get 'reviews/create'

resources :cocktails, only: [ :index, :new, :show, :create ] do
  resources :doses, only: [ :new, :create ]
  resources :reviews, only: [ :new, :create ]
end
resources :doses, only: [ :destroy ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :photo, presence: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :title, presence: true
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(user_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.cocktail = Cocktail.find(params[:cocktail_id])
    if @review.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-1 col-md-4 col-md-offset-4">
      <%= simple_form_for [@cocktail] do |f| %>
      <%= f.input :name %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "ajouter un cocktail", class: "btn btn-primary" %>
      <%= link_to "home", cocktails_path, class: "btn btn-primary text-center" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.verifiedbusinesses.com.au/sites/default/files/listing_pics/photo%20-%20cocktails.jpg');">
  <div class="banner-content">
    <h1>Mister Cocktail</h1>
    <p>Créer votre propre cocktail n'a jamais était aussi simple</p>
    <%= link_to 'AJOUTER UN COCKTAIL', new_cocktail_path, class: 'btn btn-danger'%>
  </div>
</div>
<br>
<br>


<div class="container">
  <div class="row">
    <p><% @cocktails.each do |cocktail| %></p>
    <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.4)),
         url(<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>)">
          <div class="card-category"><p><strong>Cocktail: <%= cocktail.name.upcase %></strong> </p></div>
          <div class="card-description">
          <%= link_to cocktail_path(cocktail) do %>
           "<i class="fa fa-plus-circle fa-2x card-link" aria-hidden="true"></i>
           <% end %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
</div>

 <%= link_to cocktails_path do %>
        <i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i>
        <% end %>

app/views/cocktails/new.html.erb
<br>
<br>
<br>
<br>

 <div class="container">
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-md-4">
        <%= render 'form' %>

     </div>
   </div>
 </div>

app/views/cocktails/show.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="card-show text-center">
        <p class=""><%= @cocktail.name.upcase %></p>
        <p><%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %></p>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6">
      <div class="card-show">
        <h3>INGREDIENTS:</h3>
        <% @cocktail.doses.each do |e| %>
        <p><%= e.ingredient.name %>:<%= e.description %> cl </p>
        <p><% end %></p>
        <h3>COMMENTAIRES:</h3>
        <% @cocktail.reviews.each do |e| %>
        <p><strong>Titre:</strong> <%= e.title %> - <strong>Note:</strong> <%= e.rating %>/5</p>
        <p><strong>Commentaire:</strong> <%= e.content %></p>
        <p><% end %></p>
        <p><%= link_to "AJOUTER UN INGREDIENTS", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %></p>
        <p><%= link_to "AJOUTER UN COMMENTAIRE", new_cocktail_review_path(@cocktail), class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>

app/views/component/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/component/_navbar.html.erb
<div class="navbar-wagon">
  <a href="/" class="navbar-wagon-brand">
    <img src="#" alt="logo">
  </a>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Add a Cocktail", new_cocktail_path(@cocktail), class: "navbar-wagon-item navbar-wagon-link" %>
  </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<br>
<br>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-1 col-md-4 col-md-offset-4">xs
       <%= link_to "home", cocktails_path, class: "btn btn-primary" %>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :ingredient_id, collection: Ingredient.all, as: :select %>
        <%= f.input :description %>
        <%= f.submit "ajouter une dose", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'component/navbar' %>
    <%= yield %>
    <%= render 'component/footer' %>
  </body>
</html>

app/views/reviews/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-1 col-md-4 col-md-offset-4">
      <p><%= simple_form_for [@cocktail, @review] do |f|  %> </p>
        <p><%= f.input :title %> </p>
        <p><%= f.input :rating, collection: (0..5), as: :select %></p>
        <p><%= f.input :content %> </p>
        <p><%= f.submit "add a review", class: "btn btn-primary" %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="text-center">
<h3>Donnez nous votre avis sur le cocktail</h3>

</div>
<%= render 'form' %>